# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**You must implement your own work.** You can and are encouraged to use helper libraries like `numpy`, but you must not use 3rd-party libraries or code that solves the assignment for you. *Even if it is properly referenced*, you only get marks for work you have done. If you are unsure, ask on the forum or ask a tutor directly.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

You should also consider what *data structures* you use within your code. Certain algorithms will work much faster with certain data structures, and understanding this is considered part of understanding the algorithm itself. 

I suggest you implement *constraint satisfaction* as it is described in the unit material. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%). There is an example of constraint satisfaction on the eight-queens puzzle, and you could use this as a guide to help you get started.

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [1]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [12]:
import numpy as np
import math

class Sudoku:
    def __init__(self, values, variables = [], domains = [], constraints = [], columns = "ABCDEFGHI", numbers = "123456789", peers = {}):
        """
        Instantiates a sudoku object that contains attributes and methods to help organise
        and solve sudokus.
        """
        
        self.values = values
        
        self.variables = variables
        self.domains = domains
        self.constraints = constraints

        self.columns = columns
        self.rows = numbers

        self.peers = peers
        self.peer_groups = {}

        self.unsolvable = False

        self.create_variables()
        self.create_domains()
        self.create_constraints()
        
    def is_solved(self):
        """
        Returns a boolean of whether the object is currently in a goal state.
        """
        
        if self.unsolvable:
            return True

        for constraint in self.constraints:
            operand1 = str(self.domains[constraint[0]])
            operand2 = str(self.domains[constraint[1]])
            operator = constraint[2]

            if int(operand1) > 9 or int(operand2) > 9:
                return False

            # Check constraint by using the != operator, allowing us to
            # dynmacially use these functions for other CSP models.
            if not eval(operand1 + operator + operand2):
                return False

        return True
    
    def create_variables(self):
        """
        Loops through each element of the sudoku and populates the
        variables attribute.
        
        Should not be used more than once per object.
        """
        for character in self.columns:
            for number in self.rows:
                cell_id = character + number
                
                if cell_id not in self.variables:
                    self.variables.append(cell_id)
                    
    def create_domains(self):
        """
        Loops through all variables and assigns them as all 9 possible
        values initially.
        
        Should not be used more than once per object.
        """
        new_domains = {}

        for variable in self.variables:
            column = self.columns.find(variable[0:1])
            row = self.rows.find(variable[1:2])

            current_value = self.values[column][row]

            if current_value == 0:
                new_domains[variable] = int(self.rows)
            else:
                new_domains[variable] = current_value

        self.domains = new_domains
        
    def create_peers(self, variable):
        """
        Loops through the peer_groups for a given variable and populates the peer
        groups dictionaries.
        
        peers used to easily iterate through changed arcs without comparing redudant
        ones.
        
        peer_groups used to assess whether we can infer any values through the values
        of its peers.
        
        Should not be used more than once per object.
        """
        peers = []
        peer_groups = [ [], [], [] ]

        column = self.columns.find(variable[0:1])
        row = self.rows.find(variable[1:2])

        top_left = (math.floor(column / 3), math.floor(row / 3))

        # Add relevants rows and columns
        for character in self.columns:
            if character == variable[0:1] and str(self.columns.find(character) + 1) == variable[1:2]:
                continue

            peers.append(character + str(row + 1))
            peers.append(variable[0:1] + str(self.columns.find(character) + 1))

            if character + str(row + 1) != variable:
                peer_groups[0].append(character + str(row + 1))

            if (variable[0:1] + str(self.columns.find(character) + 1)) != variable:
                peer_groups[1].append(variable[0:1] + str(self.columns.find(character) + 1))
            
        # Add 3x3 unit peers
        for i in range (0, 3):
            for j in range (0, 3):
                column_to_add = self.columns[i + (3 * top_left[0])]
                row_to_add = self.rows[j + (3 * top_left[1])]
                square_to_add = column_to_add + row_to_add

                if square_to_add not in peers and square_to_add != variable:
                    peers.append(square_to_add)

                if square_to_add != variable:
                    peer_groups[2].append(square_to_add)

        self.peers[variable] = peers
        self.peer_groups[variable] = peer_groups
        
    def create_constraints(self):
        """
        Loops through all variables and creates all constraints according to the CSP
        model used. Also creates peer groups.
        
        Should not be used more than once per object.
        """
        constraints = []

        for variable in self.variables:
            self.create_peers(variable)

            for peer in self.peers[variable]:
                if variable != peer:
                    constraints.append([variable, peer, "!="])

        self.constraints = constraints
        
    def get_sudoku(self):
        """
        Returns a 9x9 array of variable domains.
        """
        sudoku = []

        if self.unsolvable:
            return np.full((9, 9), -1)

        for row in self.columns:
            new_row = []

            for column in self.rows:
                new_row.append(self.domains[row + column])

            sudoku.append(new_row)

        return sudoku
    
def element_should_be_removed(problem, domain2, valueA, operator):
    """
    Returns boolean of whether the element of domain should be removed given the constraint.
    
    Used in the AC3 algorithm to extend the agenda when necessary.
    """
    for valueB in str(problem.domains[domain2]):
        if eval(str(valueA) + operator + str(valueB)):
            return False

    return True

def AC3(problem):
    """
    Arc Consistency 3
    
    Returns boolean of whether the problem was adjusted.
    Used by inference to determine whether an adjustment should be inferred further.
    
    Checks all values input against all CSP constraints by using a constraint agenda
    that is appended to when an arc is affected.
    
    Provides arc consistency given the current values of every variable.
    """
    changed = False
    agenda = []

    for constraint in problem.constraints:
        agenda.append(constraint)

    count = 0

    while len(agenda) > 0:
        count += 1
        constraint = agenda.pop()
        
        domain1 = constraint[0]
        domain2 = constraint[1]
        operator = constraint[2]

        removals = []

        for value in str(problem.domains[domain1]):
            if element_should_be_removed(problem, domain2, value, operator):
                removals.append([value, domain1])

                for original_constraint in problem.constraints:
                    if original_constraint[1] == domain1 and original_constraint not in agenda:
                        agenda.append(original_constraint)

        for removal in removals:
            value = removal[0]
            domain = removal[1]

            location = str(problem.domains[domain]).find(value)
            problem.domains[domain] = str(problem.domains[domain])[:location] + str(problem.domains[domain])[location + 1:]
            changed = True

            if problem.domains[domain] == "":
                problem.unsolvable = True
                return False

            problem.domains[domain] = int(str(problem.domains[domain]))

    return changed

def valid_peer_set(problem):
    """
    Returns a boolean of whether we can infer that the current value set
    is not valid by assessing whether all possible values of the domain
    are in each peer group.
    """
    peer_groups = problem.peer_groups
    
    for variable in peer_groups:
        list = str(problem.domains[variable])
        group = peer_groups[variable]
        
        for compare in group:
            for new_variable in compare:
                domain = problem.domains[new_variable]
                for character in str(domain):
                    if character not in list:
                        list = list + character

        if len(list) != 9:
            problem.unsolvable = True
            return False

    return True

def peer_consistency(problem):
    """
    Peer Consistency
    
    Returns a boolean of whether the problem was adjusted.
    Used by inference to decide whether to infer any changes further.
    
    Checks all variables against their peer group and infers a value
    given that it cannot be any other variable in its peer group.
    
    Provides peer consistency given the current state.
    """
    changed = False

    for variable in problem.variables:
        domain = problem.domains[variable]

        if len(str(domain)) == 1:
            continue

        for value in str(domain):
            for group in problem.peer_groups[variable]:
                unique = True

                for peer in group:
                    if value in str(problem.domains[peer]):
                        unique = False
                        break

                if unique:
                    problem.domains[variable] = int(value)
                    peer_consistency(problem)
                    changed = True
                    break

    return changed

def inference(problem):
    """
    Eliminate the search tree by using inference techniques:
    AC3
    Peer Consistency
    
    Checks whether the inference can tell whether the problem is
    invalid or not.
    
    Returns the adjusted problem.
    """
    peers_changed = peer_consistency(problem)
    arcs_changed = AC3(problem)

    if not valid_peer_set(problem):
        problem.unsolvable = True
        return problem

    if peers_changed or arcs_changed:
        return inference(problem)
    else:
        return problem
    
def select_value(problem, starting_variable):
    """
    Selects the value of a domain that is the Least Constraining
    against its peers.
    
    Known as the Least Constraining Value heuristic.
    
    Returns a sorted list of values by how constraining they are
    for backtracking iteration.
    """
    possible_values = problem.domains[starting_variable]
    peers = problem.peers[starting_variable]

    constrained_variables_count = []
    least_constrained_values = []

    for value in str(possible_values):
        constrained_variables = 0

        for peer in peers:
            if str(problem.domains[peer]).find(str(value)):
                constrained_variables += 1

        # Decide where the variable goes in the order of constraining
        constrained_variables_count.append(constrained_variables)
        constrained_variables_count.sort()
        
        # Put the variable in the list in the right position according to
        # how constraining it is
        index = constrained_variables_count.index(constrained_variables)
        least_constrained_values.insert(index, value)
        
    return least_constrained_values

def select_unassigned_variable(problem):
    """
    Select which variable is the most constrained.
    
    Known as the most constraining variable heuristic.
    
    Returns an integer number for the value to try in
    the backtracking iteration.
    """
    most_constrained_variable = None
    possible_values = np.inf

    for variable in problem.variables:
        domain = problem.domains[variable]

        if domain < 10:
            continue

        if domain < possible_values:
            possible_values = domain
            most_constrained_variable = variable

    return most_constrained_variable

def backtrack(problem, depth = 0):
    """
    If the sudoku inference leaves some variables without a
    definitive answer, try them all until we find a solution.
    
    Returns an adjusted problem object.
    """
    if problem.is_solved():
        return problem

    starting_variable = select_unassigned_variable(problem)
    possible_values = select_value(problem, starting_variable)

    column = problem.columns.find(starting_variable[0:1])
    row = problem.rows.find(starting_variable[1:2])

    select_value(problem, starting_variable)

    for character in possible_values:
        value = int(character)
        
        new_values = problem.values.copy()
        new_values[column][row] = value

        new_sudoku = Sudoku(new_values)
        new_sudoku = inference(new_sudoku)

        if new_sudoku is not False:
            if not new_sudoku.unsolvable:
                result = backtrack(new_sudoku, depth + 1)

                if not new_sudoku.unsolvable:
                    return result

        # Remove from domain
        location = possible_values.index(character)
        new_str = possible_values[:location] + possible_values[location + 1:]

        new_domain = ""
        for element in new_str:
            new_domain = new_domain + str(element)

        problem.domains[starting_variable] = new_domain

    problem.unsolvable = True
    return problem

def sudoku_solver(sudoku):
    """
    Solves a Sudoku puzzle and returns its unique solution.

    Input
        sudoku : 9x9 numpy array
            Empty cells are designated by 0.

    Output
        9x9 numpy array of integers
            It contains the solution, if there is one. If there is no solution, all array entries should be -1.
    """
    
    problem = Sudoku(sudoku)
    problem = inference(problem)
    
    # Inference will immediately set to boolean False
    if problem is not False:
        
        # No need to backtrack if we're already finished
        if not problem.is_solved():
            problem = backtrack(problem)
                    
    
    return problem.get_sudoku()

All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up – many more than 15 of each. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 20 seconds each on the test machine to count as successful – if it takes longer, it will timeout. Note that this is a maximum, not a goal. Higher grades require better performance on harder puzzles. As a very rough benchmark, you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms and data structures. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [16]:
SKIP_TESTS = False

def tests():
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", end_time-start_time, "seconds to solve.\n")

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        if count < len(sudokus):
            break
            
if not SKIP_TESTS:
    tests()

Testing very_easy sudokus
This is very_easy sudoku number 0
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]]
This is your solution for very_easy sudoku number 0
[[1, 7, 4, 3, 8, 2, 9, 5, 6], [2, 9, 5, 4, 6, 7, 1, 3, 8], [3, 8, 6, 9, 5, 1, 4, 7, 2], [4, 6, 1, 5, 2, 3, 8, 9, 7], [7, 3, 8, 1, 4, 9, 6, 2, 5], [9, 5, 2, 8, 7, 6, 3, 1, 4], [5, 2, 9, 6, 3, 4, 7, 8, 1], [6, 1, 7, 2, 9, 8, 5, 4, 3], [8, 4, 3, 7, 1, 5, 2, 6, 9]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.046875 seconds to solve.

This is very_easy sudoku number 1
[[0 9 3 1 5 2 6 0 8]
 [8 6 2 7 0 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 0 3 6]
 [5 0 6 8 3 9 4 1 7]
 [3 4 1 5 6 7 2 8 9]
 [6 1 4 2 7 8 9 5 3]
 [7 3 9 6 1 5 8 4 2]
 [2 8 5 3 9 4 7 6 1]]
This is your solution for very_easy sudoku number 1
[[4, 9, 3, 1, 5, 2, 6, 7, 8], [8, 6, 2, 7, 4, 3, 1, 9, 5], [1, 5, 

This is your solution for easy sudoku number 5
[[6, 4, 5, 3, 2, 8, 7, 1, 9], [3, 8, 7, 9, 1, 6, 4, 5, 2], [2, 9, 1, 4, 5, 7, 6, 3, 8], [5, 6, 3, 2, 9, 1, 8, 7, 4], [9, 7, 8, 6, 4, 5, 1, 2, 3], [1, 2, 4, 8, 7, 3, 5, 9, 6], [7, 3, 9, 5, 6, 4, 2, 8, 1], [8, 5, 6, 1, 3, 2, 9, 4, 7], [4, 1, 2, 7, 8, 9, 3, 6, 5]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.046875 seconds to solve.

This is easy sudoku number 6
[[6 4 1 3 8 2 0 7 9]
 [5 2 9 4 1 7 8 6 3]
 [3 8 7 0 6 0 2 4 1]
 [8 1 2 6 7 3 4 9 5]
 [4 9 0 8 2 1 0 3 6]
 [7 3 6 5 9 4 1 8 2]
 [9 6 4 1 5 8 3 2 7]
 [1 7 8 2 3 6 9 5 4]
 [2 5 3 7 4 9 6 1 8]]
This is your solution for easy sudoku number 6
[[6, 4, 1, 3, 8, 2, 5, 7, 9], [5, 2, 9, 4, 1, 7, 8, 6, 3], [3, 8, 7, 9, 6, 5, 2, 4, 1], [8, 1, 2, 6, 7, 3, 4, 9, 5], [4, 9, 5, 8, 2, 1, 7, 3, 6], [7, 3, 6, 5, 9, 4, 1, 8, 2], [9, 6, 4, 1, 5, 8, 3, 2, 7], [1, 7, 8, 2, 3, 6, 9, 5, 4], [2, 5, 3, 7, 4, 9, 6, 1, 8]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.0

This is your solution for medium sudoku number 4
[[-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.015625 seconds to solve.

This is medium sudoku number 5
[[0 8 5 0 1 3 0 0 9]
 [6 3 4 0 0 2 1 7 5]
 [0 2 0 5 7 4 0 3 0]
 [2 4 8 3 6 7 9 5 1]
 [9 6 0 4 5 8 0 2 3]
 [3 5 7 2 0 0 4 8 0]
 [5 7 3 1 0 0 8 9 2]
 [4 9 6 0 2 5 3 1 0]
 [8 1 2 0 3 9 5 6 4]]
This is your solution for medium sudoku number 5
[[7, 8, 5, 6, 1, 3, 2, 4, 9], [6, 3, 4, 9, 8, 2, 1, 7, 5], [1, 2, 9, 5, 7, 4, 6, 3, 8], [2, 4, 8, 3, 6, 7, 9, 5, 1], [9, 6, 1, 4, 5, 8, 7, 2, 3], [3, 5, 7, 2, 9, 1, 4, 8, 6], [5, 7, 3, 1, 4, 6, 8, 9, 2], [4, 9, 6, 8, 2, 5, 3, 1, 7], [8, 1, 2, 7, 3, 9, 5, 6, 4]]
Is your solution correct?
Yes! Correct solution.
This 

This is your solution for hard sudoku number 2
[[4, 2, 5, 8, 1, 6, 9, 7, 3], [8, 9, 3, 7, 5, 4, 6, 2, 1], [6, 1, 7, 3, 2, 9, 5, 4, 8], [9, 4, 1, 6, 8, 7, 2, 3, 5], [5, 8, 2, 4, 3, 1, 7, 6, 9], [7, 3, 6, 2, 9, 5, 1, 8, 4], [2, 7, 9, 1, 4, 8, 3, 5, 6], [3, 5, 4, 9, 6, 2, 8, 1, 7], [1, 6, 8, 5, 7, 3, 4, 9, 2]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 3.1875 seconds to solve.

This is hard sudoku number 3
[[0 0 0 0 0 0 0 5 0]
 [2 0 7 0 0 9 0 0 0]
 [6 0 0 3 5 1 0 0 0]
 [5 0 0 0 0 0 0 1 0]
 [0 0 3 0 0 0 0 0 8]
 [0 0 0 8 2 0 5 3 0]
 [0 0 0 0 7 0 8 0 4]
 [0 0 6 2 0 0 0 0 0]
 [0 8 0 0 0 0 7 0 0]]
This is your solution for hard sudoku number 3
[[8, 3, 1, 7, 4, 2, 6, 5, 9], [2, 5, 7, 6, 8, 9, 1, 4, 3], [6, 9, 4, 3, 5, 1, 2, 8, 7], [5, 6, 8, 9, 3, 7, 4, 1, 2], [4, 2, 3, 1, 6, 5, 9, 7, 8], [1, 7, 9, 8, 2, 4, 5, 3, 6], [9, 1, 2, 5, 7, 3, 8, 6, 4], [7, 4, 6, 2, 1, 8, 3, 9, 5], [3, 8, 5, 4, 9, 6, 7, 2, 1]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 1.062

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [15]:
def submission_tests():
    import sys
    import pathlib

    fail = False;

    if not SKIP_TESTS:
        fail = True;
        print("You must set the SKIP_TESTS constant to True in the cell above.")

    p1 = pathlib.Path('./readme.txt')
    p2 = pathlib.Path('./readme.md')
    if not (p1.is_file() or p2.is_file()):
        fail = True;
        print("You must include a separate file called readme.txt or readme.md in your submission.")

    p3 = pathlib.Path('./sudoku.ipynb')
    if not p3.is_file():
        fail = True
        print("This notebook file must be named sudoku.ipynb")

    if "sudoku_solver" not in globals():
        fail = True;
        print("You must include a function called sudoku_solver which accepts a numpy array.")
    else: 
        sudoku = np.load("data/very_easy_puzzle.npy")[0]
        solution = np.load("data/very_easy_solution.npy")[0]

        if not np.array_equal(sudoku_solver(sudoku), solution):
            print("Warning:")
            print("Your sudoku_solver function does not correctly solve the first sudoku.")
            print()
            print("Your assignment is unlikely to get any marks from the autograder. While we will")
            print("try to check it manually to assign some partial credit, we encourage you to ask")
            print("for help on the forum or directly to a tutor.")
            print()
            print("Please use the readme file to explain your code anyway.")

    if fail:
        print()
        sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
    else:
        print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
        print("assignment page, without changing any filenames.")
        print()
        print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")
        
submission_tests()

All checks passed. When you are ready to submit, upload the notebook and readme file to the
assignment page, without changing any filenames.

If you need to submit multiple files, you can archive them in a .zip file. (No other format.)


In [ ]:
# This is a TEST CELL. Do not delete or change.