# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**You must implement your own work.** You can and are encouraged to use helper libraries like `numpy`, but you must not use 3rd-party libraries or code that solves the assignment for you. *Even if it is properly referenced*, you only get marks for work you have done. If you are unsure, ask on the forum or ask a tutor directly.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

You should also consider what *data structures* you use within your code. Certain algorithms will work much faster with certain data structures, and understanding this is considered part of understanding the algorithm itself. 

I suggest you implement *constraint satisfaction* as it is described in the unit material. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%). There is an example of constraint satisfaction on the eight-queens puzzle, and you could use this as a guide to help you get started.

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [13]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [14]:
# Sudoku Solver #

import numpy as np
import time
import math

difficulties = ["very_easy", "easy", "medium", "hard"]

"""
Sudoku class allows us to instantiate objects that can abstract the problem.
"""
class Sudoku:
    def __init__(self, values, variables = [], constraints = [], peers = {}, peer_groups = {}):
        """
        Instantiates a new Sudoku object that can abstract each state and be manipulated to keep track of state progress.

        @param values: 2D List of values, or 0 where there is no value
        @param variables: List of all variables (squares) in the state (sudoku). For example: "A1", "I9".
        @param constraints: List of all constraints in the state. For example: ["A1", "I9", "!="]
        @param peers: Dictionary of every variable's peers where the key is the variable and the value is the list of peers.
        @param peer_groups: Dictionary of every variable's peer groups, such as the list of variables in its row, column and unit.

        @returns Newly created Sudoku object
        """

        # Values are the initial inputs in the Sudoku.
        # Used to create constraints and restrict domains.
        self.values = values

        self.columns = "ABCDEFGHI"
        self.rows = "123456789"

        # Peers dictionaries allow us easy look up of a variable's peers without
        # having to iterate through the whole state.
        self.peers = peers
        self.peer_groups = peer_groups
        
        # Typical CSP formulation
        self.variables = variables or self.create_variables()
        self.constraints = constraints or self.create_constraints()
        self.domains = self.create_domains()

        self.unsolvable = False

    def is_solved(self):
        """
        Assesses the domains of the whole table and returns whether the state is a
        goal state.

        @returns Boolean of whether the state is a goal state.
        """
        if self.unsolvable:
            return True

        for constraint in self.constraints:
            operand1 = constraint[0]
            operand2 = constraint[1]
            operator = constraint[2]
        
            domain1 = str(self.domains[operand1])
            domain2 = str(self.domains[operand2])

            if not eval(domain1 + operator + domain2):
                return False

        return True

    def create_variables(self):
        """
        Generates a list of all variables in a Sudoku state, such as "A1", "I9"

        @returns List of newly created variables
        """
        variables = []

        for character in self.columns:
            for number in self.rows:
                cell_id = character + number
                
                if cell_id not in variables:
                    variables.append(cell_id)

        return variables

    def create_domains(self):
        """
        Generates a dictionary for the domain of each variable to be all 9 numbers 
        except values that already have a set value, where the domain is simply
        that value.

        Keys are strings
        Domains are integers to allow integer comparison when assessing states

        ["A1"] = 123456789
        ["I9"] = 7

        @returns List of newly created dictionary of each variable's domain.
        """
        new_domains = {}

        for variable in self.variables:
            column = self.columns.find(variable[0:1])
            row = self.rows.find(variable[1:2])

            current_value = self.values[column][row]

            # If there is no set value assigned to a variable, it has a value of 0
            if current_value == 0:
                new_domains[variable] = int(self.rows)
            else:
                new_domains[variable] = current_value

        return new_domains

    def create_peers(self, variable):
        """
        Generates the lists of peers and peer groups for the variable.

        Peers is simply a list of the peer variables.
        Peer groups are split into 3 lists representing peers in, respectively, the same:
            - row
            - column
            - unit

        @param variable: String of the variable name to generate peers for

        @returns None
        """
        peers = []
        peer_groups = [ [], [], [] ]

        variable_column = variable[0:1]
        variable_row = variable[1:2]

        column = self.columns.find(variable_column)
        row = self.rows.find(variable_row)

        # Top left of the unit allows us to easy generate the unit peers.
        top_left = (math.floor(column / 3), math.floor(row / 3))

        for peer_column in self.columns:
            peer_row = self.columns.find(peer_column) + 1

            # Don't generate the variable as its own peer
            if peer_column == variable_column and str(peer_row) == variable_row:
                continue

            peers.append(peer_column + str(row + 1))
            peers.append(variable_column + str(peer_row))

            if peer_column + str(row + 1) != variable:
                peer_groups[0].append(peer_column + str(row + 1))

            if (variable_column + str(peer_row)) != variable:
                peer_groups[1].append(variable_column + str(peer_row))

        for i in range (0, 3):
            for j in range (0, 3):
                column_to_add = self.columns[i + (3 * top_left[0])]
                row_to_add = self.rows[j + (3 * top_left[1])]
                square_to_add = column_to_add + row_to_add

                if square_to_add not in peers and square_to_add != variable:
                    peers.append(square_to_add)

                if square_to_add != variable:
                    peer_groups[2].append(square_to_add)

        self.peers[variable] = peers
        self.peer_groups[variable] = peer_groups

    def create_constraints(self):
        """
        Generates a list of all constraints for the Sudoku CSP

        @returns List of generated constraints.
        """
        constraints = []

        for variable in self.variables:
            self.create_peers(variable)

            for peer in self.peers[variable]:
                if variable != peer and not [peer, variable, "!="] in constraints:
                    constraints.append([variable, peer, "!="])

        return constraints

    def get_sudoku(self):
        """
        Generates a typical array of values from the state's domains.
        Or generates a numpy array of -1 if the state is a non-solvable
        state.

        @returns Array of values in the state or numpy array of -1s if the state is unsolvable
        """
        sudoku = []

        if self.unsolvable:
            return np.full((9, 9), -1)

        for row in self.columns:
            new_row = []

            for column in self.rows:
                new_row.append(self.domains[row + column])

            sudoku.append(new_row)

        return sudoku

def element_should_be_removed(problem, domain2, valueA, operator):
    """
    Determines whether a value should be removed from a variable's domain
    as one of the variable's peers has the value as an assignment.

    @param domain2: int of the domain we're checking against
    @param valueA: character of the value we're assessing is in the domain
    @param operator: a string representing the Python notation for a comparison, for example: "!=", "==", ">"

    @returns boolean of whether the element should be removed from the domain
    """
    for valueB in str(problem.domains[domain2]):
        if eval(str(valueA) + operator + str(valueB)):
            return False

    return True

def AC3(problem):
    """
    Arc-Consistency 3 Algorithm

    Given the current problem's state, iterate through the constraints
    and remove values from variable's domains when an inconsistency is
    detected.

    Follow this up by checking any peers that may have been affected by
    this removal for further inference.

    This provides complete arc consistency in the state by manipulating
    the problem parameter directly.

    @param problem: CSP object to manipulate for arc-consistency

    @returns boolean: whether any values in the domain were removed
    """

    # Keep track of whether any values have been changed so inference
    # knows to keep arc consistency after a potential peer consistency
    # check.
    changed = False
    agenda = []

    for constraint in problem.constraints:
        # Add both the constraint, and the reverse of the constraint to
        # the agenda.
        agenda.append(constraint)
        agenda.append([constraint[1], constraint[0], constraint[2]])

    while len(agenda) > 0:
        constraint = agenda.pop()
        
        domain1 = constraint[0]
        domain2 = constraint[1]
        operator = constraint[2]

        # Keep track of removals to remove them
        # after the initial iteration has completed as
        # the domains should be immutable while they're
        # being iterated through
        removals = []

        for value in str(problem.domains[domain1]):
            if element_should_be_removed(problem, domain2, value, operator):
                removals.append([value, domain1])

                for original_constraint in problem.constraints:
                    if original_constraint[1] == domain1 and original_constraint not in agenda:
                        agenda.append(original_constraint)

        for removal in removals:
            value = removal[0]
            domain = removal[1]

            location = str(problem.domains[domain]).find(value)
            problem.domains[domain] = str(problem.domains[domain])[:location] + str(problem.domains[domain])[location + 1:]
            changed = True

            if problem.domains[domain] == "":
                problem.unsolvable = True
                return False

            problem.domains[domain] = int(problem.domains[domain])

    return changed

def valid_peer_set(problem):
    """
    Determine whether we can render the state as unsolvable by seeing
    whether there are any variable domains which cannot be put into
    a peer group. 
    
    For example, if there is no place for a 7 in row A, we know the
    state is unsolvable.

    @returns boolean of whether all peer groups are consistent
    """
    peer_groups = problem.peer_groups
    
    for variable in peer_groups:
        list = str(problem.domains[variable])
        group = peer_groups[variable]
        
        for compare in group:
            for new_variable in compare:
                domain = problem.domains[new_variable]
                for character in str(domain):
                    if character not in list:
                        list = list + character

        # If a number hasn't been seen in any domain in the peer
        # group, we know it can't be assigned into this peer group
        if len(list) != 9:
            problem.unsolvable = True
            return False

    return True

# Peer consistency
def peer_consistency(problem):
    """
    If there is only 1 place that a value can go in a peer group,
    we know the value must go there.
    """
    # Keep track of whether any domains have been changed so
    # inference knows to keep peer consistency if any domains
    # were changed by a further arc consistency check.
    changed = False

    for variable in problem.variables:
        domain = problem.domains[variable]

        # A variable has 1 domain if it is already assigned
        if len(str(domain)) == 1:
            continue

        for value in str(domain):
            for group in problem.peer_groups[variable]:
                unique = True

                for peer in group:
                    if value in str(problem.domains[peer]):
                        unique = False
                        break

                if unique:
                    problem.domains[variable] = int(value)

                    # We may be able to infer further values after
                    # this variable is assigned.
                    peer_consistency(problem)

                    changed = True
                    break

    return changed

def inference(problem):
    """
    Given the assignments of the states, we are able to reduce and remove
    values from each variables domain through arc consistency and peer
    consistency.

    @returns the mutated CSP object after inference
    """
    arcs_changed = AC3(problem)
    peers_changed = peer_consistency(problem)

    if problem.unsolvable:
        return problem

    if not valid_peer_set(problem):
        problem.unsolvable = True
        return problem

    if (peers_changed or arcs_changed):
        return inference(problem)
    else:
        return problem

def select_unassigned_variable(problem):
    """
    Select the most constrained variable in a state to give us
    the best chance of reducing the search tree to find a solution.

    @returns the variable name of the most constrained variable
    """
    most_constrained_variable = None
    possible_values = np.inf

    for variable in problem.variables:
        domain = problem.domains[variable]

        if domain < 10:
            continue

        if domain < possible_values:
            possible_values = domain
            most_constrained_variable = variable

    return most_constrained_variable

def backtrack(problem, depth = 0):
    """
    Assign a value to a variable given suitable heuristics and check
    whether the new state is a goal state. If not, backtrack up to
    the previous assignment and try a new value.

    @param problem: CSP to search for goal states

    @returns new or mutated CSP object in a goal state or unsolvable state
    """
    if problem.is_solved():
        return problem

    # Most constrained value heuristic
    starting_variable = select_unassigned_variable(problem)
    possible_values = str(problem.domains[starting_variable])

    column = problem.columns.find(starting_variable[0:1])
    row = problem.rows.find(starting_variable[1:2])

    for character in possible_values:
        value = int(character)
        
        new_values = problem.values.copy()
        new_values[column][row] = value

        # Create new sudoku object with new assignments so we can keep
        # the previous assignments in the stack in case this one fails
        new_sudoku = Sudoku(new_values, variables = problem.variables, constraints = problem.constraints, peers = problem.peers, peer_groups = problem.peer_groups)

        if depth != 0:
            inference(new_sudoku)

        if not new_sudoku.unsolvable:
            result = backtrack(new_sudoku, depth + 1)

            if not result.unsolvable:
                return result

        # Remove from domain
        location = possible_values.index(character)
        problem.domains[starting_variable] = possible_values[:location] + possible_values[location + 1:]

    # If we've tried every value with no success, we know there are no possibilites
    problem.unsolvable = True
    return problem

def sudoku_solver(sudoku):
    """
    Solves a Sudoku puzzle and returns its unique solution.

    Input
        sudoku : 9x9 numpy array
            Empty cells are designated by 0.

    Output
        9x9 numpy array of integers
            It contains the solution, if there is one. If there is no solution, all array entries should be -1.
    """
    
    problem = Sudoku(sudoku)
    problem = inference(problem)
            
    if not problem.is_solved():
        problem = backtrack(problem)
                    
    
    return problem.get_sudoku()

All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up – many more than 15 of each. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 20 seconds each on the test machine to count as successful – if it takes longer, it will timeout. Note that this is a maximum, not a goal. Higher grades require better performance on harder puzzles. As a very rough benchmark, you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms and data structures. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [15]:
SKIP_TESTS = False

def tests():
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", end_time-start_time, "seconds to solve.\n")

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        if count < len(sudokus):
            break
            
if not SKIP_TESTS:
    tests()

Testing very_easy sudokus
This is very_easy sudoku number 0
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]]
This is your solution for very_easy sudoku number 0
[[1, 7, 4, 3, 8, 2, 9, 5, 6], [2, 9, 5, 4, 6, 7, 1, 3, 8], [3, 8, 6, 9, 5, 1, 4, 7, 2], [4, 6, 1, 5, 2, 3, 8, 9, 7], [7, 3, 8, 1, 4, 9, 6, 2, 5], [9, 5, 2, 8, 7, 6, 3, 1, 4], [5, 2, 9, 6, 3, 4, 7, 8, 1], [6, 1, 7, 2, 9, 8, 5, 4, 3], [8, 4, 3, 7, 1, 5, 2, 6, 9]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.0625 seconds to solve.

This is very_easy sudoku number 1
[[0 9 3 1 5 2 6 0 8]
 [8 6 2 7 0 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 0 3 6]
 [5 0 6 8 3 9 4 1 7]
 [3 4 1 5 6 7 2 8 9]
 [6 1 4 2 7 8 9 5 3]
 [7 3 9 6 1 5 8 4 2]
 [2 8 5 3 9 4 7 6 1]]
This is your solution for very_easy sudoku number 1
[[4, 9, 3, 1, 5, 2, 6, 7, 8], [8, 6, 2, 7, 4, 3, 1, 9, 5], [1, 5, 7,

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [16]:
def submission_tests():
    import sys
    import pathlib

    fail = False;

    if not SKIP_TESTS:
        fail = True;
        print("You must set the SKIP_TESTS constant to True in the cell above.")

    p1 = pathlib.Path('./readme.txt')
    p2 = pathlib.Path('./readme.md')
    if not (p1.is_file() or p2.is_file()):
        fail = True;
        print("You must include a separate file called readme.txt or readme.md in your submission.")

    p3 = pathlib.Path('./sudoku.ipynb')
    if not p3.is_file():
        fail = True
        print("This notebook file must be named sudoku.ipynb")

    if "sudoku_solver" not in globals():
        fail = True;
        print("You must include a function called sudoku_solver which accepts a numpy array.")
    else: 
        sudoku = np.load("data/very_easy_puzzle.npy")[0]
        solution = np.load("data/very_easy_solution.npy")[0]

        if not np.array_equal(sudoku_solver(sudoku), solution):
            print("Warning:")
            print("Your sudoku_solver function does not correctly solve the first sudoku.")
            print()
            print("Your assignment is unlikely to get any marks from the autograder. While we will")
            print("try to check it manually to assign some partial credit, we encourage you to ask")
            print("for help on the forum or directly to a tutor.")
            print()
            print("Please use the readme file to explain your code anyway.")

    if fail:
        print()
        sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
    else:
        print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
        print("assignment page, without changing any filenames.")
        print()
        print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")
        
submission_tests()

You must set the SKIP_TESTS constant to True in the cell above.



Your submission is not ready! Please read and follow the instructions above.

In [17]:
# This is a TEST CELL. Do not delete or change.